# Описательные статистики

In [2]:
# Импортируем библиотеки
import pandas as pd

In [3]:
# Подключим данные
df = pd.read_csv('sleep75.csv')
# Выведем первые 10 наблюдений
df.head(n=10)

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
0,32,0,1,0.0,0.0,12,0,0,1,3529,...,0,3438,0,3438,0,14,0,13,7.070004,1024
1,31,0,2,0.0,0.0,14,9500,1,1,2140,...,0,5020,0,5020,0,11,0,0,1.429999,961
2,44,0,3,0.0,0.0,17,42500,1,1,4595,...,1,2815,0,2815,0,21,0,0,20.529997,1936
3,30,0,4,0.0,0.0,12,42500,1,1,3211,...,1,3786,0,3786,0,12,0,12,9.619998,900
4,64,0,5,0.0,0.0,14,2500,1,1,4052,...,1,2580,0,2580,0,44,0,33,2.750000,4096
5,41,0,6,0.0,0.0,12,0,1,1,4812,...,0,1205,0,0,1205,23,0,23,19.249998,1681
6,35,0,7,0.0,0.0,12,8250,1,1,4787,...,1,2113,0,2113,0,17,1,0,1.440000,1225
7,47,0,8,0.0,0.0,13,0,1,1,3544,...,0,3608,0,3608,0,28,0,24,15.010007,2209
8,32,0,9,0.0,0.0,17,18750,1,1,4359,...,0,2353,1,2353,0,9,0,11,4.329998,1024
9,30,0,10,0.0,0.0,15,11750,1,1,4211,...,1,2851,0,2851,0,9,0,7,2.959999,900

In [4]:
# Выведем последние 10 наблюдений
df.tail(n=10)

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
696,36,0,697,0.182331,0.030075,16,9500,1,0,4776,...,0,2281,0,2281,0,14,0,14,NaN,1296
697,47,0,698,0.182331,0.030075,10,9500,1,0,5882,...,0,1183,1,1183,0,31,0,28,NaN,2209
698,52,0,699,0.182331,0.030075,10,0,0,0,4797,...,0,2275,0,2275,0,36,0,29,NaN,2704
699,61,0,700,0.182331,0.030075,17,27500,1,0,4362,...,0,2725,0,2725,0,38,0,30,NaN,3721
700,32,0,701,0.182331,0.030075,16,10500,1,0,4707,...,0,2388,0,2388,0,10,0,0,NaN,1024
701,45,0,702,0.182331,0.030075,12,5500,1,0,5069,...,1,2026,0,2026,0,27,0,18,NaN,2025
702,34,0,703,0.182331,0.030075,10,2500,0,0,5885,...,0,675,1,465,210,18,0,4,NaN,1156
703,37,0,704,0.182331,0.030075,12,3500,1,0,4719,...,1,1851,0,1851,0,19,0,17,NaN,1369
704,54,0,705,0.182331,0.030075,17,32500,1,0,5149,...,1,1961,1,1481,480,31,0,22,NaN,2916
705,30,0,706,0.182331,0.030075,16,6750,1,0,4747,...,0,2363,0,2363,0,8,1,9,NaN,900

<div class="alert alert-block alert-warning">  
<b>Внимание:</b> индексация в Python начинается с нуля (первое наблюдение имеет нулевой индекс). 

Поэтому часто будем говорить о индексах наблюдения. 

</div>

In [5]:
df.index

RangeIndex(start=0, stop=706, step=1)

In [6]:
# Выведем типы данных в столбцах
df.dtypes

age           int64
black         int64
case          int64
clerical    float64
construc    float64
educ          int64
earns74       int64
gdhlth        int64
inlf          int64
leis1         int64
leis2         int64
leis3         int64
smsa          int64
lhrwage     float64
lothinc     float64
male          int64
marr          int64
prot          int64
rlxall        int64
selfe         int64
sleep         int64
slpnaps       int64
south         int64
spsepay       int64
spwrk75       int64
totwrk        int64
union         int64
worknrm       int64
workscnd      int64
exper         int64
yngkid        int64
yrsmarr       int64
hrwage      float64
agesq         int64
dtype: object

In [7]:
# Выведем тип данных для столбца age
df['age'].dtype

dtype('int64')

In [8]:
# Выведем тип данных для столбцов age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].dtypes

age       int64
sleep     int64
totwrk    int64
dtype: object

## Описательные статистики

In [9]:
# Выведем описательные статистики
df.describe()

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
count,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,...,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,532.000000,706.000000
mean,38.815864,0.049575,353.500000,0.182331,0.030075,12.780453,9767.705382,0.890935,0.753541,4690.723796,...,0.480170,2122.920680,0.218130,2093.252125,29.668555,20.035411,0.128895,11.769122,5.082839,1635.144476
std,11.342637,0.217219,203.948932,0.335413,0.148366,2.784702,9323.588151,0.311942,0.431254,908.049561,...,0.499961,947.470123,0.413269,945.301457,148.834262,12.377520,0.335321,11.591227,3.704385,950.102976
min,23.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1745.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.350000,529.000000
25%,29.000000,0.000000,177.250000,0.000000,0.000000,12.000000,2500.000000,1.000000,1.000000,4109.750000,...,0.000000,1553.500000,0.000000,1538.000000,0.000000,10.000000,0.000000,0.000000,2.890002,841.000000
50%,36.000000,0.000000,353.500000,0.000000,0.000000,12.000000,8250.000000,1.000000,1.000000,4620.000000,...,0.000000,2288.000000,0.000000,2275.000000,0.000000,17.000000,0.000000,9.000000,4.379999,1296.000000
75%,48.000000,0.000000,529.750000,0.182331,0.030075,16.000000,13750.000000,1.000000,1.000000,5203.750000,...,1.000000,2691.750000,0.000000,2635.500000,0.000000,30.000000,0.000000,20.000000,6.210001,2304.000000
max,65.000000,1.000000,706.000000,1.000000,1.000000,17.000000,42500.000000,1.000000,1.000000,7417.000000,...,1.000000,6415.000000,1.000000,6415.000000,1337.000000,55.000000,1.000000,43.000000,35.509987,4225.000000

In [10]:
# Выведем описательные статистики для столбца age
df['age'].describe()

count    706.000000
mean      38.815864
std       11.342637
min       23.000000
25%       29.000000
50%       36.000000
75%       48.000000
max       65.000000
Name: age, dtype: float64

In [11]:
# Выведем описательные статистики для столбцов age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].describe()

              age        sleep       totwrk
count  706.000000   706.000000   706.000000
mean    38.815864  3266.355524  2122.920680
std     11.342637   444.413448   947.470123
min     23.000000   755.000000     0.000000
25%     29.000000  3015.000000  1553.500000
50%     36.000000  3270.500000  2288.000000
75%     48.000000  3532.250000  2691.750000
max     65.000000  4695.000000  6415.000000

In [12]:
# Количество наблюдений всех признаков (столбцов)
df.count()

age         706
black       706
case        706
clerical    706
construc    706
educ        706
earns74     706
gdhlth      706
inlf        706
leis1       706
leis2       706
leis3       706
smsa        706
lhrwage     532
lothinc     706
male        706
marr        706
prot        706
rlxall      706
selfe       706
sleep       706
slpnaps     706
south       706
spsepay     706
spwrk75     706
totwrk      706
union       706
worknrm     706
workscnd    706
exper       706
yngkid      706
yrsmarr     706
hrwage      532
agesq       706
dtype: int64

## Выборочное среднее (среднее арифметическое)

In [13]:
# Средние значения для всех признаков (столбцов)
df.mean()

age           38.815864
black          0.049575
case         353.500000
clerical       0.182331
construc       0.030075
educ          12.780453
earns74     9767.705382
gdhlth         0.890935
inlf           0.753541
leis1       4690.723796
leis2       4573.995751
leis3       4518.784703
smsa           0.399433
lhrwage        1.430977
lothinc        6.228292
male           0.566572
marr           0.821530
prot           0.662890
rlxall      3438.294618
selfe          0.131728
sleep       3266.355524
slpnaps     3383.083569
south          0.184136
spsepay     5144.178470
spwrk75        0.480170
totwrk      2122.920680
union          0.218130
worknrm     2093.252125
workscnd      29.668555
exper         20.035411
yngkid         0.128895
yrsmarr       11.769122
hrwage         5.082839
agesq       1635.144476
dtype: float64

In [14]:
# Среднее значение age
df['age'].mean()

38.815864022662886

In [15]:
# Средние значения для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].mean()

age         38.815864
sleep     3266.355524
totwrk    2122.920680
dtype: float64

## Медиана

In [16]:
# Медианные значения для всех признаков (столбцов)
df.median()

age           36.000000
black          0.000000
case         353.500000
clerical       0.000000
construc       0.000000
educ          12.000000
earns74     8250.000000
gdhlth         1.000000
inlf           1.000000
leis1       4620.000000
leis2       4519.000000
leis3       4469.000000
smsa           0.000000
lhrwage        1.477046
lothinc        8.612685
male           1.000000
marr           1.000000
prot           1.000000
rlxall      3428.000000
selfe          0.000000
sleep       3270.500000
slpnaps     3369.000000
south          0.000000
spsepay        0.000000
spwrk75        0.000000
totwrk      2288.000000
union          0.000000
worknrm     2275.000000
workscnd       0.000000
exper         17.000000
yngkid         0.000000
yrsmarr        9.000000
hrwage         4.379999
agesq       1296.000000
dtype: float64

In [17]:
# Медиана для age
df['age'].median()

36.0

In [18]:
# Медианные значения для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].median()

age         36.0
sleep     3270.5
totwrk    2288.0
dtype: float64

## Выборочная дисперсия

In [56]:
# смещённая (biased) для всех признаков (столбцов)
df.var(ddof=0)

age         1.284732e+02
black       4.711738e-02
case        4.153625e+04
clerical    1.123426e-01
construc    2.198130e-02
educ        7.743584e+00
earns74     8.680617e+07
gdhlth      9.716995e-02
inlf        1.857169e-01
leis1       8.233861e+05
leis2       8.216361e+05
leis3       8.149949e+05
smsa        2.398864e-01
lhrwage     3.974582e-01
lothinc     1.778080e+01
male        2.455681e-01
marr        1.466186e-01
prot        2.234670e-01
rlxall      2.704659e+05
selfe       1.143758e-01
sleep       1.972236e+05
slpnaps     2.486951e+05
south       1.502299e-01
spsepay     6.791501e+07
spwrk75     2.496068e-01
totwrk      8.964281e+05
union       1.705495e-01
worknrm     8.923291e+05
workscnd    2.212026e+04
exper       1.529860e+02
yngkid      1.122812e-01
yrsmarr     1.341662e+02
hrwage      1.369667e+01
agesq       9.014171e+05
dtype: float64

In [57]:
# смещённая (biased) для age
df['age'].var(ddof=0)

128.47317609482462

In [58]:
# смещённая (biased) для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].var(ddof=0)

age          128.473176
sleep     197223.563404
totwrk    896428.104190
dtype: float64

In [55]:
# несмещённая (unbiased) для всех признаков (столбцов)
df.var(ddof=1)

age         1.286554e+02
black       4.718422e-02
case        4.159517e+04
clerical    1.125020e-01
construc    2.201248e-02
educ        7.754568e+00
earns74     8.692930e+07
gdhlth      9.730778e-02
inlf        1.859804e-01
leis1       8.245540e+05
leis2       8.228015e+05
leis3       8.161509e+05
smsa        2.402266e-01
lhrwage     3.982067e-01
lothinc     1.780602e+01
male        2.459165e-01
marr        1.468266e-01
prot        2.237840e-01
rlxall      2.708496e+05
selfe       1.145380e-01
sleep       1.975033e+05
slpnaps     2.490478e+05
south       1.504430e-01
spsepay     6.801134e+07
spwrk75     2.499608e-01
totwrk      8.976996e+05
union       1.707914e-01
worknrm     8.935948e+05
workscnd    2.215164e+04
exper       1.532030e+02
yngkid      1.124405e-01
yrsmarr     1.343565e+02
hrwage      1.372247e+01
agesq       9.026957e+05
dtype: float64

In [59]:
# несмещённая (biased) для age, sleep и totwrk
df['age'].var(ddof=1)

128.65540755027826

In [60]:
# несмещённая (biased) для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].var(ddof=1)

age          128.655408
sleep     197503.313140
totwrk    897699.633416
dtype: float64

## Стандартное отклонение

In [19]:
# Стандартные отклонения для всех признаков
df.std()

age           11.342637
black          0.217219
case         203.948932
clerical       0.335413
construc       0.148366
educ           2.784702
earns74     9323.588151
gdhlth         0.311942
inlf           0.431254
leis1        908.049561
leis2        907.084066
leis3        903.410701
smsa           0.490129
lhrwage        0.631036
lothinc        4.219718
male           0.495900
marr           0.383180
prot           0.473058
rlxall       520.432096
selfe          0.338435
sleep        444.413448
slpnaps      499.046930
south          0.387870
spsepay     8246.898857
spwrk75        0.499961
totwrk       947.470123
union          0.413269
worknrm      945.301457
workscnd     148.834262
exper         12.377520
yngkid         0.335321
yrsmarr       11.591227
hrwage         3.704385
agesq        950.102976
dtype: float64

In [20]:
# Стандартное отклонение age
df['age'].std()

11.34263671067174

In [21]:
# Стандартные отклонения age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].std()

age        11.342637
sleep     444.413448
totwrk    947.470123
dtype: float64

## Min

In [22]:
# Минимальные значения для всех признаков
df.min()

age           23.000000
black          0.000000
case           1.000000
clerical       0.000000
construc       0.000000
educ           1.000000
earns74        0.000000
gdhlth         0.000000
inlf           0.000000
leis1       1745.000000
leis2       1677.000000
leis3       1677.000000
smsa           0.000000
lhrwage       -1.049822
lothinc        0.000000
male           0.000000
marr           0.000000
prot           0.000000
rlxall      1380.000000
selfe          0.000000
sleep        755.000000
slpnaps     1335.000000
south          0.000000
spsepay        0.000000
spwrk75        0.000000
totwrk         0.000000
union          0.000000
worknrm        0.000000
workscnd       0.000000
exper          0.000000
yngkid         0.000000
yrsmarr        0.000000
hrwage         0.350000
agesq        529.000000
dtype: float64

In [23]:
# Минимальное значение age
df['age'].min()

23

In [24]:
# Минимальные значения для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].min()

age        23
sleep     755
totwrk      0
dtype: int64

## Max

In [25]:
# Максимальные значения для всех признаков
df.max()

age            65.000000
black           1.000000
case          706.000000
clerical        1.000000
construc        1.000000
educ           17.000000
earns74     42500.000000
gdhlth          1.000000
inlf            1.000000
leis1        7417.000000
leis2        7297.000000
leis3        7282.000000
smsa            1.000000
lhrwage         3.569814
lothinc        10.657280
male            1.000000
marr            1.000000
prot            1.000000
rlxall       6110.000000
selfe           1.000000
sleep        4695.000000
slpnaps      6110.000000
south           1.000000
spsepay     75000.000000
spwrk75         1.000000
totwrk       6415.000000
union           1.000000
worknrm      6415.000000
workscnd     1337.000000
exper          55.000000
yngkid          1.000000
yrsmarr        43.000000
hrwage         35.509987
agesq        4225.000000
dtype: float64

In [26]:
# Максимальное значение age
df['age'].max()

65

In [27]:
# Максимальные значения для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].max()

age         65
sleep     4695
totwrk    6415
dtype: int64

## Разброс / размах выборки

In [28]:
# Разброс / размах выборки для всех признаков
df.max() - df.min()

age            42.000000
black           1.000000
case          705.000000
clerical        1.000000
construc        1.000000
educ           16.000000
earns74     42500.000000
gdhlth          1.000000
inlf            1.000000
leis1        5672.000000
leis2        5620.000000
leis3        5605.000000
smsa            1.000000
lhrwage         4.619636
lothinc        10.657280
male            1.000000
marr            1.000000
prot            1.000000
rlxall       4730.000000
selfe           1.000000
sleep        3940.000000
slpnaps      4775.000000
south           1.000000
spsepay     75000.000000
spwrk75         1.000000
totwrk       6415.000000
union           1.000000
worknrm      6415.000000
workscnd     1337.000000
exper          55.000000
yngkid          1.000000
yrsmarr        43.000000
hrwage         35.159987
agesq        3696.000000
dtype: float64

In [29]:
# Разброс / размах выборки для age
df['age'].max() - df['age'].min()

42

In [30]:
# Разброс / размах выборки для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].max() - df[['age', 'sleep', 'totwrk']].min()

age         42
sleep     3940
totwrk    6415
dtype: int64

## Квартили

In [31]:
# Первые квартили для всех признаков
df.quantile(0.25)

age           29.000000
black          0.000000
case         177.250000
clerical       0.000000
construc       0.000000
educ          12.000000
earns74     2500.000000
gdhlth         1.000000
inlf           1.000000
leis1       4109.750000
leis2       3986.250000
leis3       3933.250000
smsa           0.000000
lhrwage        1.061257
lothinc        0.000000
male           0.000000
marr           1.000000
prot           0.000000
rlxall      3150.000000
selfe          0.000000
sleep       3015.000000
slpnaps     3105.750000
south          0.000000
spsepay        0.000000
spwrk75        0.000000
totwrk      1553.500000
union          0.000000
worknrm     1538.000000
workscnd       0.000000
exper         10.000000
yngkid         0.000000
yrsmarr        0.000000
hrwage         2.890002
agesq        841.000000
Name: 0.25, dtype: float64

In [32]:
# Первый квартиль для age
df['age'].quantile(0.25)

29.0

In [33]:
# Первые квартили для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].quantile(0.25)

age         29.0
sleep     3015.0
totwrk    1553.5
Name: 0.25, dtype: float64

In [34]:
# Вторые квартили (или медиана) для всех признаков 
df.quantile(0.5)

age           36.000000
black          0.000000
case         353.500000
clerical       0.000000
construc       0.000000
educ          12.000000
earns74     8250.000000
gdhlth         1.000000
inlf           1.000000
leis1       4620.000000
leis2       4519.000000
leis3       4469.000000
smsa           0.000000
lhrwage        1.477046
lothinc        8.612685
male           1.000000
marr           1.000000
prot           1.000000
rlxall      3428.000000
selfe          0.000000
sleep       3270.500000
slpnaps     3369.000000
south          0.000000
spsepay        0.000000
spwrk75        0.000000
totwrk      2288.000000
union          0.000000
worknrm     2275.000000
workscnd       0.000000
exper         17.000000
yngkid         0.000000
yrsmarr        9.000000
hrwage         4.379999
agesq       1296.000000
Name: 0.5, dtype: float64

In [35]:
# Вторые квартили (или медиана) для age
df['age'].quantile(0.5)

36.0

In [36]:
# Вторые квартили (или медиана) для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].quantile(0.5)

age         36.0
sleep     3270.5
totwrk    2288.0
Name: 0.5, dtype: float64

In [37]:
# Третьи квартили для всех признаков 
df.quantile(0.75)

age            48.000000
black           0.000000
case          529.750000
clerical        0.182331
construc        0.030075
educ           16.000000
earns74     13750.000000
gdhlth          1.000000
inlf            1.000000
leis1        5203.750000
leis2        5071.250000
leis3        5028.250000
smsa            1.000000
lhrwage         1.826161
lothinc         9.328213
male            1.000000
marr            1.000000
prot            1.000000
rlxall       3719.500000
selfe           0.000000
sleep        3532.250000
slpnaps      3655.000000
south           0.000000
spsepay      8900.000000
spwrk75         1.000000
totwrk       2691.750000
union           0.000000
worknrm      2635.500000
workscnd        0.000000
exper          30.000000
yngkid          0.000000
yrsmarr        20.000000
hrwage          6.210001
agesq        2304.000000
Name: 0.75, dtype: float64

In [38]:
# Третий квартиль для age
df['age'].quantile(0.75)

48.0

In [39]:
# Третьи квартили для age, sleep, totwrk
df[['age', 'sleep', 'totwrk']].quantile(0.75)

age         48.00
sleep     3532.25
totwrk    2691.75
Name: 0.75, dtype: float64

## Межквартильный разброс

In [40]:
# Межквартильный разброс для всех признаков
df.quantile(0.75) - df.quantile(0.25)

age            19.000000
black           0.000000
case          352.500000
clerical        0.182331
construc        0.030075
educ            4.000000
earns74     11250.000000
gdhlth          0.000000
inlf            0.000000
leis1        1094.000000
leis2        1085.000000
leis3        1095.000000
smsa            1.000000
lhrwage         0.764904
lothinc         9.328213
male            1.000000
marr            0.000000
prot            1.000000
rlxall        569.500000
selfe           0.000000
sleep         517.250000
slpnaps       549.250000
south           0.000000
spsepay      8900.000000
spwrk75         1.000000
totwrk       1138.250000
union           0.000000
worknrm      1097.500000
workscnd        0.000000
exper          20.000000
yngkid          0.000000
yrsmarr        20.000000
hrwage          3.319999
agesq        1463.000000
dtype: float64

In [41]:
# Межквартильный разброс для age
df['age'].quantile(0.75) - df['age'].quantile(0.25)

19.0

In [42]:
# Межквартильный разброс для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].quantile(0.75) - df[['age', 'sleep', 'totwrk']].quantile(0.25)

age         19.00
sleep      517.25
totwrk    1138.25
dtype: float64

## Мода

In [43]:
# Мода для всех признаков
df.mode()

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
0,28.0,0.0,1,0.0,0.0,12.0,0.0,1.0,1.0,3776.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,5.77,784.0
1,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,4012.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,4112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,4154.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,4362.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,NaN,NaN,702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,NaN,NaN,703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
703,NaN,NaN,704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
704,NaN,NaN,705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,NaN,NaN,706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# Мода для age
df['age'].mode()

0    28
Name: age, dtype: int64

In [45]:
# Мода для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].mode()

    age  sleep  totwrk
0  28.0   2985     0.0
1   NaN   3150     NaN
2   NaN   3203     NaN
3   NaN   3218     NaN
4   NaN   3308     NaN
5   NaN   3405     NaN

## Ковариация

In [46]:
# Ковариация для всех признаков
df.cov()

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
age,128.655408,-0.156816,162.812766,-4.512605e-02,3.108829e-02,-8.396512,7.475960e+03,-0.357700,-3.759428e-01,7.716467e+01,...,-0.498692,-5.327182e+02,-0.171125,-5.590627e+02,26.344556,137.051920,-1.215948,78.085086,4.222128,10692.174159
black,-0.156816,0.047184,2.548227,7.201514e-03,2.666242e-04,-0.016051,-1.459145e+02,-0.001678,8.880317e-04,8.314421e+00,...,0.004531,-5.702445e+00,0.001937,-4.560035e+00,-1.142411,-0.140765,0.002112,-0.104850,-0.028694,-13.571712
case,162.812766,2.548227,41595.166667,9.236181e+00,2.835649e-02,-17.551064,-1.457791e+05,0.495745,-6.565106e+01,5.303701e+04,...,-5.376596,-6.155752e+04,-0.709220,-6.020239e+04,-1355.130496,180.363830,-3.482979,253.680142,-94.139216,14688.321986
clerical,-0.045126,0.007202,9.236181,1.125020e-01,-4.138005e-03,0.007196,-1.500467e+02,0.001592,-3.138055e-08,3.931361e+01,...,0.017205,-4.648068e+01,-0.011819,-4.369566e+01,-2.785018,-0.052322,-0.009468,0.006895,-0.234323,-2.926308
construc,0.031088,0.000267,0.028356,-4.138005e-03,2.201248e-02,-0.022268,-5.391938e+01,-0.000235,3.484731e-08,-3.862160e+00,...,-0.003391,1.143662e+00,0.000683,-4.873363e-02,1.192396,0.053357,-0.000363,-0.030960,0.008163,2.374494
educ,-8.396512,-0.016051,-17.551064,7.196188e-03,-2.226844e-02,7.754568,6.898574e+03,0.212901,-3.716473e-02,3.154920e+01,...,0.109825,8.602370e+01,-0.108071,8.547671e+01,0.546987,-16.151080,0.097842,-5.653597,2.607864,-701.041995
earns74,7475.959858,-145.914452,-145779.078014,-1.500467e+02,-5.391938e+01,6898.573524,8.692930e+07,369.309666,-4.811243e+01,-7.043685e+05,...,592.904788,1.022965e+06,352.870030,9.112966e+05,111668.288028,577.386334,50.551504,2086.717698,14886.178773,545446.729150
gdhlth,-0.357700,-0.001678,0.495745,1.591746e-03,-2.346299e-04,0.212901,3.693097e+02,0.097308,-4.223173e-03,-1.632946e+01,...,0.014146,3.058424e+01,-0.007382,2.781335e+01,2.770892,-0.570601,0.002730,0.139323,0.116409,-35.697696
inlf,-0.375943,0.000888,-65.651064,-3.138055e-08,3.484731e-08,-0.037165,-4.811243e+01,-0.004223,1.859804e-01,-2.319299e+01,...,0.033404,2.839177e+01,0.001354,2.793599e+01,0.455785,-0.338778,0.009117,-0.447054,0.000000,-30.907605
leis1,77.164672,8.314421,53037.014894,3.931361e+01,-3.862160e+00,31.549203,-7.043685e+05,-16.329458,-2.319299e+01,8.245540e+05,...,52.515792,-7.623752e+05,-2.640375,-7.491716e+05,-13203.538485,45.615468,-0.825341,635.211317,-473.732015,18362.378969
leis2,-122.936954,8.563332,52800.274468,3.423164e+01,-2.847634e+00,87.410413,-5.659503e+05,-11.614649,-2.473013e+01,7.984641e+05,...,57.497079,-7.357266e+05,-0.918221,-7.225699e+05,-13156.771623,-210.347367,4.020407,615.650081,-388.253268,2194.758062
leis3,-159.510622,8.805015,51004.595745,3.233751e+01,-3.318172e+00,87.403729,-5.686458e+05,-11.385217,-2.231980e+01,7.868738e+05,...,54.319129,-7.215005e+05,1.574689,-7.092041e+05,-12296.346638,-246.914351,6.047648,503.307669,-415.543473,-212.551829
smsa,0.138903,0.002865,2.443972,1.545086e-02,1.013170e-03,0.214060,5.627760e+02,0.005328,-4.962530e-03,3.219417e+01,...,0.003677,-1.760090e+01,-0.007820,-1.421433e+01,-3.386571,-0.075157,-0.009005,-0.497720,0.258243,10.957812
lhrwage,0.367363,-0.008419,-18.126724,-3.406175e-02,5.492567e-03,0.466654,2.309362e+03,0.013071,0.000000e+00,-1.224187e+02,...,-0.027136,1.406934e+02,0.016738,1.361895e+02,4.503887,-0.099291,0.006904,0.754316,2.002780,19.980219
lothinc,2.058572,-0.002875,-17.725928,7.161991e-02,-3.039400e-02,0.421982,-1.262564e+04,0.046459,1.825660e-01,2.038845e+02,...,0.815607,-2.726350e+02,-0.209508,-2.814620e+02,8.826970,1.636590,-0.051971,11.508867,-1.307414,169.931851
male,0.179652,-0.005433,-22.373050,-5.166373e-02,8.777260e-03,0.049388,6.743516e+02,0.007980,-1.193820e-02,-1.689653e+02,...,-0.039813,1.768790e+02,0.008153,1.670555e+02,9.823515,0.130263,0.017648,0.391988,0.664931,12.095333
marr,0.076310,-0.002487,0.137589,-6.119020e-03,-1.535755e-03,-0.034983,1.088381e+02,0.011713,-2.913226e-03,-3.376128e-02,...,0.084399,-9.120559e+00,-0.000731,-1.186841e+01,2.747855,0.111293,0.017363,2.103418,0.045961,3.034332
prot,0.600249,-0.001704,-6.800000,-5.420468e-03,2.026365e-04,-0.128017,6.023246e+01,0.001479,1.183373e-02,-3.793154e+01,...,-0.002439,3.222429e+01,-0.008631,3.055036e+01,1.673924,0.728266,0.000960,0.543335,-0.077918,48.793454
rlxall,692.228795,-3.102570,10552.926241,1.414317e+01,2.174510e+00,-173.427425,-4.543191e+05,-19.199028,-6.071967e+00,-2.449867e+04,...,-0.055142,-1.761992e+05,-2.384924,-1.753673e+05,-831.866751,865.656219,-8.849376,461.573082,-137.134806,60681.587162
selfe,0.102304,-0.000866,5.769504,-1.241401e-02,2.207641e-03,0.033217,4.363169e+02,-0.001216,-3.131818e-02,-2.339051e+01,...,-0.005186,2.312252e+01,-0.018846,2.000646e+01,3.116063,0.069088,-0.007074,0.111307,0.103001,8.487324
sleep,455.553501,-2.611976,8520.507092,7.167067e+00,2.718497e+00,-117.572899,-3.185964e+05,-14.254787,-5.198778e+00,-6.217884e+04,...,1.748195,-1.353245e+05,1.830141,-1.353998e+05,75.325096,573.126400,-1.976387,329.669433,-78.946264,42106.656364
slpnaps,655.655126,-2.860886,8757.247518,1.224904e+01,1.703972e+00,-173.434109,-4.570146e+05,-18.969596,-3.661644e+00,-3.608893e+04,...,-3.233092,-1.619730e+05,0.107986,-1.620015e+05,28.558234,829.089235,-6.822134,349.230669,-164.425011,58274.277271
south,-0.079521,0.005043,-5.855319,2.756889e-03,2.399619e-03,-0.054552,-7.276837e+01,0.000253,1.707753e-02,-3.213914e+01,...,-0.009109,1.859051e+01,-0.007598,1.614925e+01,2.441259,-0.024969,0.007438,-0.116292,-0.087594,-4.352882
spsepay,-1108.124537,9.962771,188275.641135,4.721459e+02,-8.911575e+01,2989.349876,1.870850e+07,233.761336,9.525823e+01,1.490482e+06,...,2677.891487,-1.519368e+06,-8.989340,-1.513753e+06,-5614.272678,-4097.474414,-186.057079,12594.495164,-2500.799637,-177722.739296
spwrk75,-0.498692,0.004531,-5.376596,1.720524e-02,-3.391451e-03,0.109825,5.929048e+02,0.014146,3.340365e-02,5.251579e+01,...,0.249961,-5.426399e+01,0.005750,-5.455811e+01,0.294127,-0.608517,-0.002405,0.859954,-0.133657,-41.836847
totwrk,-532.718173,-5.702445,-61557.521986,-4.648068e+01,1.143662e+00,86.023696,1.022965e+06,30.584244,2.839177e+01,-7.623752e+05,...,-54.263986,8.976996e+05,0.810234,8.845714e+05,13128.213389,-618.741868,2.801728,-964.880751,552.678279,-60469.035332
union,-0.171125,0.001937,-0.709220,-1.181944e-02,6.825577e-04,-0.108071,3.528700e+02,-0.007382,1.354148e-03,-2.640375e+00,...,0.005750,8.102345e-01,0.170791,-4.535925e+00,5.346160,-0.063054,-0.005461,-0.159496,-0.002565,-16.606027
worknrm,-559.062729,-4.560035,-60202.391489,-4.369566e+01,-4.873363e-02,85.476708,9.112966e+05,27.813353,2.793599e+01,-7.491716e+05,...,-54.558114,8.845714e+05,-4.535925,8.935948e+05,-9023.424117,-644.539437,0.920648,-1088.784261,531.953678,-61933.931513
workscnd,26.344556,-1.142411,-1355.130496,-2.785018e+00,1.192396e+00,0.546987,1.116683e+05,2.770892,4.557853e-01,-1.320354e+04,...,0.294127,1.312821e+04,5.346160,-9.023424e+03,22151.637506,25.797569,1.881080,123.903510,20.724601,1464.896181
exper,137.051920,-0.140765,180.363830,-5.232224e-02,5.335673e-02,-16.151080,5.773863e+02,-0.570601,-3.387781e-01,4.561547e+01,...,-0.608517,-6.187419e+02,-0.063054,-6.445394e+02,25.797569,153.203000,-1.313791,83.738684,1.614264,11393.216153
yngkid,-1.215948,0.002112,-3.482979,-9.467820e-03,-3.626069e-04,0.097842,5.055150e+01,0.002730,9.117393e-03,-8.253410e-01,...,-0.002405,2.801728e+00,-0.005461,9.206477e-01,1.881080,-1.313791,0.112440,-0.693603,-0.006653,-97.275386
yrsmarr,78.085086,-0.104850,253.680142,6.894972e-03,-3.096046e-02,-5.653597,2.086718e+03,0.139323,-4.470536e-01,6.352113e+02,...,0.859954,-9.648808e+02,-0.159496,-1.088784e+03,123.903510,83.738684,-0.693603,134.356549,4.588349,6423.264609
hrwage,4.222128,-0.028694,-94.139216,-2.343227e-01,8.163043e-03,2.607864,1.488618e+04,0.116409,0.000000e+00,-4.737320e+02,...,-0.133657,5.526783e+02,-0.002565,5.319537e+02,20.724601,1.614264,-0.006653,4.588349,13.722467,300.423387
agesq,10692.174159,-13.571712,14688.321986,-2.926308e+00,2.374494e+00,-701.041995,5.454467e+05,-35.697696,-3.090760e+01,1.836238e+04,...,-41.836847,-6.046904e+04,-16.606027,-6.193393e+04,1464.896181,11393.216153,-97.275386,6423.264609,300.423387,902695.664203

In [47]:
# Ковариация для age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].cov()

               age          sleep         totwrk
age     128.655408     455.553501    -532.718173
sleep   455.553501  197503.313140 -135324.471051
totwrk -532.718173 -135324.471051  897699.633416

In [48]:
# Корреляция между признаками
df.corr()

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
age,1.000000,-0.063647,0.070381,-1.186132e-02,1.847346e-02,-0.265831,0.070692,-0.101095,-7.685537e-02,0.007492,...,-0.087939,-0.049570,-0.036506,-0.052141,0.015605,0.976197,-0.319698,0.593915,0.101466,0.992159
black,-0.063647,1.000000,0.057520,9.884287e-02,8.273070e-03,-0.026535,-0.072047,-0.024758,9.479743e-03,0.042153,...,0.041718,-0.027707,0.021575,-0.022207,-0.035336,-0.052356,0.028990,-0.041643,-0.035258,-0.065761
case,0.070381,0.057520,1.000000,1.350178e-01,9.371230e-04,-0.030903,-0.076664,0.007792,-7.464261e-01,0.286384,...,-0.052729,-0.318562,-0.008414,-0.312264,-0.044643,0.071449,-0.050929,0.107309,-0.165320,0.075802
clerical,-0.011861,0.098843,0.135018,1.000000e+00,-8.315270e-02,0.007704,-0.047980,0.015213,-2.169436e-07,0.129078,...,0.102599,-0.146260,-0.085268,-0.137812,-0.055789,-0.012603,-0.084180,0.001773,-0.163671,-0.009183
construc,0.018473,0.008273,0.000937,-8.315270e-02,1.000000e+00,-0.053898,-0.038979,-0.005070,5.446296e-07,-0.028667,...,-0.045721,0.008136,0.011132,-0.000347,0.053999,0.029055,-0.007289,-0.018003,0.012890,0.016845
educ,-0.265831,-0.026535,-0.030903,7.704485e-03,-5.389849e-02,1.000000,0.265704,0.245089,-3.094701e-02,0.012477,...,0.078883,0.032604,-0.093907,0.032471,0.001320,-0.468586,0.104782,-0.175153,0.261361,-0.264969
earns74,0.070692,-0.072047,-0.076664,-4.798032e-02,-3.897870e-02,0.265704,1.000000,0.126980,-1.196577e-02,-0.083197,...,0.127194,0.115801,0.091580,0.103397,0.080472,0.005003,0.016169,0.019309,0.489183,0.061574
gdhlth,-0.101095,-0.024758,0.007792,1.521318e-02,-5.069617e-03,0.245089,0.126980,1.000000,-3.139291e-02,-0.057649,...,0.090705,0.103480,-0.057258,0.094321,0.059682,-0.147783,0.026103,0.038532,0.098537,-0.120447
inlf,-0.076855,0.009480,-0.746426,-2.169436e-07,5.446296e-07,-0.030947,-0.011966,-0.031393,1.000000e+00,-0.059226,...,0.154926,0.069485,0.007598,0.068527,0.007101,-0.063467,0.063049,-0.089433,NaN,-0.075433
leis1,0.007492,0.042153,0.286384,1.290783e-01,-2.866726e-02,0.012477,-0.083197,-0.057649,-5.922618e-02,1.000000,...,0.115676,-0.886122,-0.007036,-0.872773,-0.097696,0.004059,-0.002711,0.060350,-0.143310,0.021284
leis2,-0.011949,0.043461,0.285409,1.125123e-01,-2.115934e-02,0.034605,-0.066919,-0.041047,-6.321866e-02,0.969389,...,0.126783,-0.856058,-0.002449,-0.842679,-0.097454,-0.018735,0.013218,0.058554,-0.117070,0.002547
leis3,-0.015566,0.044869,0.276823,1.067189e-01,-2.475593e-02,0.034743,-0.067511,-0.040400,-5.728905e-02,0.959203,...,0.120263,-0.842919,0.004218,-0.830454,-0.091451,-0.022081,0.019964,0.048064,-0.125577,-0.000248
smsa,0.024985,0.026910,0.024449,9.398575e-02,1.393277e-02,0.156836,0.123152,0.034849,-2.347789e-02,0.072336,...,0.015004,-0.037902,-0.038604,-0.030679,-0.046424,-0.012389,-0.054791,-0.087608,0.142607,0.023531
lhrwage,0.051826,-0.060730,-0.186869,-1.396643e-01,5.091425e-02,0.274545,0.445494,0.064950,NaN,-0.217397,...,-0.086025,0.238863,0.063978,0.232230,0.048510,-0.012910,0.031410,0.106415,0.856767,0.033839
lothinc,0.043010,-0.003136,-0.020597,5.060229e-02,-4.854785e-02,0.035911,-0.320913,0.035295,1.003236e-01,0.053210,...,0.386600,-0.068192,-0.120139,-0.070561,0.014055,0.031334,-0.036729,0.235299,-0.086959,0.042386
male,0.031939,-0.050434,-0.221213,-3.106074e-01,1.192973e-01,0.035764,0.145851,0.051588,-5.582278e-02,-0.375227,...,-0.160580,0.376458,0.039782,0.356366,0.133098,0.021222,0.106131,0.068194,0.360521,0.025672
marr,0.017558,-0.029883,0.001761,-4.761014e-02,-2.701376e-02,-0.032785,0.030465,0.097994,-1.762943e-02,-0.000097,...,0.440555,-0.025122,-0.004618,-0.032766,0.048182,0.023466,0.135132,0.473580,0.032103,0.008335
prot,0.111867,-0.016580,-0.070481,-3.416191e-02,2.887145e-03,-0.097180,0.013656,0.010021,5.800607e-02,-0.088303,...,-0.010313,0.071896,-0.044149,0.068317,0.023775,0.124378,0.006054,0.099089,-0.044996,0.108562
rlxall,0.117266,-0.027445,0.099423,8.102191e-02,2.816195e-02,-0.119667,-0.093630,-0.118261,-2.705402e-02,-0.051840,...,-0.000212,-0.357334,-0.011089,-0.356463,-0.010740,0.134384,-0.050709,0.076515,-0.071487,0.122722
selfe,0.026651,-0.011779,0.083588,-1.093597e-01,4.396622e-02,0.035246,0.138275,-0.011514,-2.145795e-01,-0.076112,...,-0.030647,0.072110,-0.134741,0.062535,0.061863,0.016493,-0.062336,0.028374,0.096959,0.026395
sleep,0.090373,-0.027057,0.094006,4.808108e-02,4.122942e-02,-0.095004,-0.076890,-0.102825,-2.712568e-02,-0.154080,...,0.007868,-0.321384,0.009965,-0.322300,0.001139,0.104191,-0.013262,0.063997,-0.049450,0.099722
slpnaps,0.115830,-0.026391,0.086041,7.317801e-02,2.301371e-02,-0.124800,-0.098221,-0.121855,-1.701379e-02,-0.079638,...,-0.012958,-0.342559,0.000524,-0.343406,0.000384,0.134223,-0.040768,0.060373,-0.089579,0.122904
south,-0.018075,0.059854,-0.074019,2.119109e-02,4.169864e-02,-0.050506,-0.020122,0.002092,1.020953e-01,-0.091251,...,-0.046975,0.050587,-0.047403,0.044045,0.042289,-0.005201,0.057187,-0.025866,-0.058332,-0.011812
spsepay,-0.011846,0.005561,0.111939,1.706890e-01,-7.283319e-02,0.130169,0.243313,0.090867,2.678418e-02,0.199034,...,0.649481,-0.194449,-0.002638,-0.194175,-0.004574,-0.040141,-0.067281,0.131753,-0.091552,-0.022682
spwrk75,-0.087939,0.041718,-0.052729,1.025994e-01,-4.572094e-02,0.078883,0.127194,0.090705,1.549261e-01,0.115676,...,1.000000,-0.114554,0.027830,-0.115439,0.003953,-0.098334,-0.014345,0.148392,-0.072180,-0.088075
totwrk,-0.049570,-0.027707,-0.318562,-1.462604e-01,8.135754e-03,0.032604,0.115801,0.103480,6.948538e-02,-0.886122,...,-0.114554,1.000000,0.002069,0.987636,0.093097,-0.052761,0.008819,-0.087857,0.159840,-0.067173
union,-0.036506,0.021575,-0.008414,-8.526757e-02,1.113197e-02,-0.093907,0.091580,-0.057258,7.598005e-03,-0.007036,...,0.027830,0.002069,1.000000,-0.011611,0.086917,-0.012327,-0.039406,-0.033296,-0.001670,-0.042292
worknrm,-0.052141,-0.022207,-0.312264,-1.378123e-01,-3.474754e-04,0.032471,0.103397,0.094321,6.852675e-02,-0.872773,...,-0.115439,0.987636,-0.011611,1.000000,-0.064135,-0.055087,0.002904,-0.099367,0.154521,-0.068958
workscnd,0.015605,-0.035336,-0.044643,-5.578855e-02,5.399868e-02,0.001320,0.080472,0.059682,7.101071e-03,-0.097696,...,0.003953,0.093097,0.086917,-0.064135,1.000000,0.014004,0.037691,0.071821,0.038025,0.010359
exper,0.976197,-0.052356,0.071449,-1.260296e-02,2.905502e-02,-0.468586,0.005003,-0.147783,-6.346702e-02,0.004059,...,-0.098334,-0.052761,-0.012327,-0.055087,0.014004,1.000000,-0.316542,0.583664,0.035753,0.968818
yngkid,-0.319698,0.028990,-0.050929,-8.417992e-02,-7.288536e-03,0.104782,0.016169,0.026103,6.304865e-02,-0.002711,...,-0.014345,0.008819,-0.039406,0.002904,0.037691,-0.316542,1.000000,-0.178451,-0.005156,-0.305331
yrsmarr,0.593915,-0.041643,0.107309,1.773466e-03,-1.800295e-02,-0.175153,0.019309,0.038532,-8.943277e-02,0.060350,...,0.148392,-0.087857,-0.033296,-0.099367,0.071821,0.583664,-0.178451,1.000000,0.110267,0.583251
hrwage,0.101466,-0.035258,-0.165320,-1.636706e-01,1.289004e-02,0.261361,0.489183,0.098537,NaN,-0.143310,...,-0.072180,0.159840,-0.001670,0.154521,0.038025,0.035753,-0.005156,0.110267,1.000000,0.086673
agesq,0.992159,-0.065761,0.075802,-9.182675e-03,1.684480e-02,-0.264969,0.061574,-0.120447,-7.543296e-02,0.021284,...,-0.088075,-0.067173,-0.042292,-0.068958,0.010359,0.968818,-0.305331,0.583251,0.086673,1.000000

In [49]:
# Корреляция между age, sleep и totwrk
df[['age', 'sleep', 'totwrk']].corr()

             age     sleep    totwrk
age     1.000000  0.090373 -0.049570
sleep   0.090373  1.000000 -0.321384
totwrk -0.049570 -0.321384  1.000000